name: Build & Certify

on:
  push:
    branches:
      main
    workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    name: Build & Certify

    steps:

      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GraalVM set up
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'maven'
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'

      - name: Certify
        run: mvn -B clean verify

      - name: Certify native
        run: |
            mvn -B clean verify -Pnative \
              -Dquarkus.http.host=0.0.0.0 \
              -Dquarkus.container-image.build=true \
              -Dquarkus.native.container-build=true \
              -Dquarkus.test.arg-line="--add-host host.docker.internal:host-gateway"
